"""add start_date and end_date to reports

Revision ID: ac1c773cb7f4
Revises: b9a614c16366
Create Date: 2025-12-12 18:42:19.219759+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1c773cb7f4'
down_revision = 'b9a614c16366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'end_date')
    op.drop_column('reports', 'start_date')
    # ### end Alembic commands ###
