"""Add password reset and notifications

Revision ID: 712fa932fce8
Revises: d5644ef4a6ac
Create Date: 2025-12-29 16:59:21.517561+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '712fa932fce8'
down_revision = 'd5644ef4a6ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campos de reset de contraseña a users
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    
    # Crear tabla de notificaciones
    op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('related_id', sa.Integer(), nullable=True),
        sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'])
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.create_table('refunds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget_amount', sa.INTEGER(), autoincrement=False, nullable=False, comment='Presupuesto original del viaje (centavos)'),
    sa.Column('total_expenses', sa.INTEGER(), autoincrement=False, nullable=False, comment='Total gastado en el viaje (centavos)'),
    sa.Column('excess_amount', sa.INTEGER(), autoincrement=False, nullable=False, comment='Excedente a devolver (centavos)'),
    sa.Column('refunded_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Monto ya devuelto (centavos)'),
    sa.Column('status', postgresql.ENUM('pending', 'partial', 'completed', 'waived', 'disputed', 'overdue', name='refund_status'), server_default=sa.text("'pending'::refund_status"), autoincrement=False, nullable=False),
    sa.Column('refund_method', postgresql.ENUM('cash', 'transfer', 'payroll', 'check', 'other', name='refund_method'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Fecha l??mite para devolver'),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waive_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Raz??n por la que el admin exoner?? la devoluci??n'),
    sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('budget_amount >= 0 AND total_expenses >= 0 AND excess_amount >= 0 AND refunded_amount >= 0', name=op.f('positive_amounts')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('refunds_report_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('refunds_trip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refunds_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey')),
    comment='Devoluciones por excedentes de presupuesto en viajes'
    )
    op.create_index(op.f('idx_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    op.create_index(op.f('idx_refunds_trip_id'), 'refunds', ['trip_id'], unique=False)
    op.create_index(op.f('idx_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('idx_refunds_due_date'), 'refunds', ['due_date'], unique=False)
    # ### end Alembic commands ###
